version: '2'

services:
  traefik:
    image: traefik:v1.7.3-alpine
    networks:
      default: {}
      traefik:
        aliases:
          - traefik-idc-demo_traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: --docker --docker.watch --constraints='tag==traefik-idc-demo'

  openresty:
    build:
      context: openresty-docker
    env_file: ./secrets.env

  nginx:
    image: nginx:1.15.5-alpine
    volumes:
      - ./nginx-root:/usr/share/nginx/html:ro
    labels:
      traefik.enable: true
      traefik.frontend.auth.forward.address: http://openresty/
      traefik.frontend.headers.customResponseHeaders: "Cache-Control:no-store,must-revalidate"
      traefik.frontend.rule: Host:traefik-idc-demo.loki.xlipse.net
      traefik.port: 80
      traefik.tags: traefik-idc-demo

networks:
  default:
    external:
      name: lokinet_trusted
  traefik:
    external:
      name: lokinet_traefik
