version: '2'

services:
  openresty:
    build:
      context: openresty-docker
    env_file: ./secrets.env
    networks:
      - default

  nginx:
    image: nginx:1.15.7-alpine
    volumes:
      - ./nginx-root:/usr/share/nginx/html:ro
    networks:
      - default
      - traefik
    labels:
      traefik.docker.network: network_traefik
      traefik.enable: true
      traefik.frontend.auth.forward.address: http://openresty/
      traefik.frontend.headers.customResponseHeaders: Cache-Control:no-store,must-revalidate
      traefik.frontend.rule: Host:traefik-idc-demo.xlipse.net
      traefik.port: 80
      traefik.tags: production

networks:
  default:
    external:
      name: network_default
  traefik:
    external:
      name: network_traefik
